### ISSUE TITLE
Bad Request Error

### ISSUE THREAD

**Issue by mistaguy** [exactonline/exactonline-api-ruby-client#18]
When i run code below i get Bad Request Error???:

<pre>
<code class="ruby">

Elmas.configure do |config|
      config.client_id = [XX]
      config.client_secret = [XXX]
    end
    Elmas.configure do |config|
      config.access_token = Elmas.authorize([XXX], [XXX]).access_token
    end
    Elmas.configure do |config|
      config.division = Elmas.authorize_division
    end

</code>
</pre>

**Comment by Marthyn** [comment]
It could be that you have not accepted the application before. The code should automatically accept it for you but it might not work. Try to do an oauth flow request with something like Postman first. Then you'll get a screen where you can press a button. After that it should work, when i get back from holiday i'll look into it though.

**Comment by Marthyn** [comment]
@mistaguy The problem was probably in the redirect uri, the readme has been updated with information on that. Please let met know if you still have problems.

**Comment by mistaguy** [comment]
@Marthyn it is quite some time but i ended up using Oath2 gem to create tokens and pass it to the Elmas. There were quite a couple of miss Exact libs that i added to my fork. Was busy the project that i didnt request for pulls
