### ISSUE TITLE
All records displayed when applying filter

### ISSUE THREAD

**Issue by maurice00001** [exactonline/exactonline-api-ruby-client#21]
When requesting SalesOrders with a particular delivery status using a filter all records are being displayed. Not only the SalesOrders with the requested delivery status.

I'm using the following code:
`Elmas::SalesOrder.new(delivery_status: ['12', '20']).find_by(filter: [:delivery_status])`

Hope you can help me out with this problem.

**Comment by maurice00001** [comment]
Got it working by the following code:
`Elmas::SalesOrder.new(delivery_status: [12, 20]).find_by(filters: [:delivery_status])`

The status id's should be without the ' and instead of filter it should be filters.

**Comment by Marthyn** [comment]
Maybe good idea to add this to the readme :)
