### ISSUE TITLE
Access GeneralJournalEntry and GeneralJournalEntryLines

### ISSUE THREAD

**Issue by Menno-de-brie** [exactonline/exactonline-api-ruby-client#24]
Do we have to add resources for GeneralJournalEntries ourselves like in the 'add resources' issue explained?

Thank you

**Comment by Marthyn** [comment]
Yes if you'd like a new resource in it you can just add the file yourself in a PR in here https://github.com/exactonline/exactonline-api-ruby-client/tree/master/lib/elmas/resources

Make sure it follows this template 

```
module Elmas
  class Layout
    include Elmas::Resource
 
    # Leave this out if all CRUD actions are valid.
    def valid_actions
      []
    end

    def base_path
      ""
    end

    def mandatory_attributes
      []
    end

    def other_attributes
      []
    end
  end
end
```
