### ISSUE TITLE
Dependency update request

### ISSUE THREAD

**Issue by karensg** [exactonline/exactonline-api-ruby-client#55]
Hi,

First of all, thanks for the great gem. We are successfully using it. However we encounter a couple of incompatibilities with other modern gems.
It would be great if you could update `faraday` en `mechanize` gems to the newest versions in order to fix that problem.

Thanks
Karens

**Comment by Marthyn** [comment]
Ah i updated all dev deps, not faraday and mechanize yet.

I'll have a look if its quick enough

**Comment by Marthyn** [comment]
@karensg I've shipped `2.4.1` just now with new faraday and mechanize versions, have fun!

**Comment by karensg** [comment]
Thanks, works great!
I think you can also close PR #37 as it solves the same problem.
