### ISSUE TITLE
OAuth 2.0

### ISSUE THREAD

**Issue by Nomad88** [exactonline/exactonline-api-ruby-client#59]
After reading the following I got excited about your code:

> If you only use the api within your app without exposing it to users you can chose to automatically login with your credentials. So this is for example when you have a rake task that shoots in invoices. Do not use this when you let other users login. Build your own OAUTH flow and then set the access token before the api request.

I see in the code you guys use a headless browser (Java dev barely able to read your code but code is code) to load the actual HTML form that Exact Online offers for login. Is this because other OAuth grant types are not supported in Exact online? (normally one would use grant_type=client_credentials for Server-to-Server communication). I'm having trouble getting this information from Exact themselves. Cheers for any help you can offer.

**Comment by Marthyn** [comment]
Hi Nomad,

From the Exact Online site:

"Exact Online currently only supports OAuth authentication based on the grant type Authorization Code."

They do not support any other form than filling out their web form. That is why the gem uses Mechanize to load in the HTMl of the webform and programmatically fill out the form, submit it and retrieve a code from a URL. Not the best implementation but it works, as long as Exact does not update their form ;).

**Comment by Marthyn** [comment]
Hi @Nomad88,

Gonna close this issue, I'm assuming you read my reply :)
