### ISSUE TITLE
Deprecate Elmas.authorize

### ISSUE THREAD

**Issue by korstiaan** [exactonline/exactonline-api-ruby-client#75]
Because Exact introduced required 2FA for all acounts, the automated fetching of the access token done in `Elmas.authorize` doesn't work anymore (it errors on the 2FA code page).

I think we should remove this functionality altogether, and rely on the refresh token functionality introduced in https://github.com/exactonline/exactonline-api-ruby-client/pull/67.

**Comment by Marthyn** [comment]
@korstiaan Agree. I will do this thursday.
