### ISSUE TITLE
Authorization Exact Online

### ISSUE THREAD

**Issue by Bramjetten** [exactonline/exactonline-api-ruby-client#79]
I know this is probably unrelated to this gem, but we're having trouble generating access/refresh tokens. When using Postman to get a new access token using OAuth 2, Exact returns this:

<img width="683" alt="schermafbeelding 2018-06-11 om 09 42 09" src="https://user-images.githubusercontent.com/423116/41218568-dffe0456-6d5b-11e8-99b0-11c45e3f6331.png">

Does anyone know a different way to get these tokens?

**Comment by Marthyn** [comment]
This seems like an Exact issue, I'm not officially affiliated with Exact, i suggest you use their customer service :). @Dahie

**Comment by Dahie** [comment]
Hi, why am I mentioned? I'm not affiliated to Exact either. :D

**Comment by Marthyn** [comment]
@Dahie I think i meant to @ another person, if you start to mention someone Github lists a list of suggestions so i think it was just an error and you showed up in the list since you contributed :). https://github.com/exactonline/exactonline-api-ruby-client/commits?author=Dahie
